### PR TITLE
iOS: Move swizzles out of FullStory.framework, and implement fsTagName and fsAttribute.

### PR DESCRIPTION
**Pull request by jwise**
Pairs with jwise/unswizzle-react-native branch in FullStory.framework.

Note that modifying an fsAttribute is an untested codepath -- I don't see a test for that in App.js.  I'll work on testing that out, in parallel.

### CODE REVIEW

**Comment by jwise** [comment]
Ah, no, the 'click to swap' does the test I'm looking for -- and that codepath is now tested, and works.  So we're good, I'd say.

**Comment by JoshMiers-FS** [comment]
In `App.js`, click the textview that says "Click to swap - false". It will bounce between false and true and on the playback the selectors should change.

**Comment by JoshMiers-FS** [comment]
The component, in playback, should switch between the following for the selector's ending:
`.fs-swap-false.fs-unmask[data-element="TouchableText"][custom_attr2_false="custom_value2_false"][data-source-file="Text.js"][data-component="Text"][custom_attr1_false="custom_value1_false"]`


`.fs-mask.fs-swap-true[data-element="TouchableText"][data-source-file="Text.js"][custom_attr1_true="custom_value1_true"][data-component="Text"][custom_attr2_true="custom_value2_true"]`

**Comment by JoshMiers-FS** [comment]
This ensures that both `fsClass` and `fsAttribute` get their values cleared before adding new ones.

**Comment by JoshMiers-FS** [comment]
btw, i didn't see that you already found the text view to click on before i wrote all of the above. ignore me...

**Pull request merged**
