### PR TITLE
detect whether Fullstory is disabled before logging API errors

### PR DESCRIPTION
**Pull request by RyanCommits**
We wouldn't want to log API errors if Fullstory is disabled.

### CODE REVIEW

**Comment by JoshMiers-FS** [comment]
I don't think this PR tackles the actual issue the customer was seeing, which is what happens when FS is not actually added to the apk due. This logic will only be triggered when FS is part of the APK and either the server response disables FS or some other constraint is hit, which is good, but not what will fix the customer's actual issue.

**Comment by RyanCommits** [comment]
> I don't think this PR tackles the actual issue the customer was seeing, which is what happens when FS is not actually added to the apk due. This logic will only be triggered when FS is part of the APK and either the server response disables FS or some other constraint is hit, which is good, but not what will fix the customer's actual issue.

The customer situation involves FS being disabled due to missing `enabledVariants` configuration. I tested this situation and this API does get triggered.

**Comment by RyanCommits** [comment]
> @JoshMiers-FS The callback is triggered because [registerStatusListener](https://github.com/cowpaths/mn/blob/master/projects/fullstory/nativemobile/android/jdk/api/src/main/java/com/fullstory/FS.java#L35-L37) will call onFSDisabled if it isn't replaced by the actual implementation when FS is applied. This is the `onFSDisabled` callback rather than the `onSessionDisabled` callback.
> 
> @RyanCommits But we can't rely on this API as it is newer than the Pages API.

Any ideas on what to use to detect FS being disabled?

**Comment by ReeceLaF** [comment]
> Any ideas on what to use to detect FS being disabled?

You could try seeing if there is a fullstory config file in the assets. I haven't tested this out, but something like the following would probably work if you have a way to access the application Context:
```java
AssetManager am = context.getAssets();
try {
    // Check if fullstory has been applied by checking if the fs-config.properties file exists or, for older clients, the fullstory.properties file
    if (am.list("fs-config.properties").length == 0 && am.list("fullstory.properties").length == 0) {
        isDisabled = true;
    }
} catch (Throwable t) {
    Log.e(TAG, "Could not determine if Fullstory is enabled. APIs may not function correctly.");
}
```
But you might not have Context access, and filesystem operations can be kind of slow, so another option could be:
```java
try {
    Class.forName("com.fullstory.instrumentation.Bootstrap");
} catch (ClassNotFoundException ignored) {
    isDisabled = true;
}
```
WDYT, @JoshMiers-FS

**Comment by RyanCommits** [comment]
Testing Option 1, but this [context](https://github.com/fullstorydev/fullstory-react-native/blob/efe843fbf0eda3e59e238a6710d6b81dbe16a0da/android/src/turbo/java/com/FullStoryModule.java#L11) doesn't have the right information, and I'm not sure how to get to the main application context. 

Option 2 works, I'll defer to @JoshMiers-FS on which option sounds best. 

With my current solution, customers with versions `1.41` - `1.47` will still get this logged incorrectly.

**Comment by JoshMiers-FS** [comment]
> > Any ideas on what to use to detect FS being disabled?
> 
> You could try seeing if there is a fullstory config file in the assets. I haven't tested this out, but something like the following would probably work if you have a way to access the application Context:
> 
> ```java
> AssetManager am = context.getAssets();
> try {
>     // Check if fullstory has been applied by checking if the fs-config.properties file exists or, for older clients, the fullstory.properties file
>     if (am.list("fs-config.properties").length == 0 && am.list("fullstory.properties").length == 0) {
>         isDisabled = true;
>     }
> } catch (Throwable t) {
>     Log.e(TAG, "Could not determine if Fullstory is enabled. APIs may not function correctly.");
> }
> ```
> 
> But you might not have Context access, and filesystem operations can be kind of slow, so another option could be:
> 
> ```java
> try {
>     Class.forName("com.fullstory.instrumentation.Bootstrap");
> } catch (ClassNotFoundException ignored) {
>     isDisabled = true;
> }
> ```
> 
> WDYT, @JoshMiers-FS

Yeah, that should work.

**Comment by ReeceLaF** [comment]
> Yeah, that should work since that class has been around since the beginning and would only exist when FS was added.

And importantly has always been kept (i.e.- not obfuscated through Proguard/minification).

> Testing Option 1, but this [context](https://github.com/fullstorydev/fullstory-react-native/blob/efe843fbf0eda3e59e238a6710d6b81dbe16a0da/android/src/turbo/java/com/FullStoryModule.java#L11) doesn't have the right information, and I'm not sure how to get to the main application context.

You probably just need to use `context.getApplicationContext()`, but let's just use option 2 since we are ok with it, and it should be faster anyway.

**Review by ReeceLaF — APPROVED** [review]
LGTM

**Pull request merged**
